version: '2'
services:
    studentexchange-app:
        image: studentexchange
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://studentexchange-mariadb:3306/studentexchange
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    studentexchange-mariadb:
        extends:
            file: mariadb.yml
            service: studentexchange-mariadb
